### ISSUE TITLE
Chapters 6-12 Produce NoSuchFileException When Loading Shader Resources

### ISSUE THREAD

**Issue by SWinxy** [lwjglgamedev/vulkanbook#7]
**Describe the bug**
The book samples code (chapters 6-12) produce `java.nio.file.NoSuchFileException` when trying to find the shader files (ShaderCompiler.java; L59). This is because the path to the file incorrectly assumes that the JDK will find the file in the module's resources using `Files.readAllBytes` and `Files.write`.

**To Reproduce**
1. Clone this repo to a fresh folder
2. Open in IDE (mine is Intellij IDEA)
3. Build and run any chapters from 6 to 12
4. Error

**Expected behavior**
Code will find the shader in the resources folder and compile it.

**Stack Trace**
```
Exception in thread "main" java.lang.RuntimeException: java.nio.file.NoSuchFileException: resources\shaders\geometry_vertex.glsl
	at org.vulkanb.eng.graph.vk.ShaderCompiler.compileShaderIfChanged(ShaderCompiler.java:67)
	at org.vulkanb.eng.graph.geometry.GeometryRenderActivity.createShaders(GeometryRenderActivity.java:142)
	at org.vulkanb.eng.graph.geometry.GeometryRenderActivity.<init>(GeometryRenderActivity.java:53)
	at org.vulkanb.eng.graph.Render.init(Render.java:61)
	at org.vulkanb.eng.Engine.<init>(Engine.java:19)
	at org.vulkanb.Main.main(Main.java:27)
Caused by: java.nio.file.NoSuchFileException: resources\shaders\geometry_vertex.glsl
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3272)
	at org.vulkanb.eng.graph.vk.ShaderCompiler.compileShaderIfChanged(ShaderCompiler.java:59)
	... 5 more
```

**Please complete the following information:**
 - OS: Windows 10
 - Java version 14.0.1

**Additional context**
The result should probably save [via resource stream](https://stackoverflow.com/questions/13000937/read-and-write-to-java-file-via-resource) as well as reading it.

**Comment by lwjglgamedev** [comment]
Sorry but I cannot reproduce the problem.

It is assumed that the working directory is the project root directory (each samples directory). Relative paths are used so they can work that way. The resources folder used for the shaders are outside the src/main folder. Therefore, its contents are not copied to the compiled classes folder (and cannot be accesed through the CLASSPATH). Maybe I should use a different name to avoid confusion (There is another resources folder inside the src/main folder which resources are accessed using resource stream).

The examples should also work, when building with maven, in the target folder by executing java -jar chapter.XX.jar.

Is it possible that you maye have set up a different working directory?

**Comment by SWinxy** [comment]
Ohhh... Interesting. I assumed it was a problem because the earlier chapters ran fine. Opening the module as its own workspace allowed it to run. If you want you can close this, but it might help people debug.

**Comment by lwjglgamedev** [comment]
I've added a comment on that in order to help other people also. I hope it is more clear now.
Thanks for reporting this !

**Comment by aftamat4ik** [comment]
i have same problem in `vscode`. It dosen't want to load relative paths of shaders.
```
Exception in thread "main" java.lang.RuntimeException: java.nio.file.NoSuchFileException: resources\shaders\fwd_vertex.glsl
        at org.vulkanb.eng.graph.vk.ShaderCompiler.compileShaderIfChanged(ShaderCompiler.java:71)
        at org.vulkanb.eng.graph.ForwardRenderActivity.<init>(ForwardRenderActivity.java:63)
        at org.vulkanb.eng.graph.Render.<init>(Render.java:39)
        at org.vulkanb.eng.Engine.<init>(Engine.java:18)
        at org.vulkanb.Main.main(Main.java:22)
Caused by: java.nio.file.NoSuchFileException: resources\shaders\fwd_vertex.glsl
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
        at org.vulkanb.eng.graph.vk.ShaderCompiler.compileShaderIfChanged(ShaderCompiler.java:57)
        ... 4 more
```
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/f92917bd-9f53-4612-b11c-dd71c441e773)
I know there is a way to fix it, but i'm only learning java and my knowlege is not enough. Yet i tried to fix function `compileShaderIfChanged` by advices from Stackoverflow, with no luck.
![image](https://github.com/lwjglgamedev/vulkanbook/assets/4356170/065c765f-bdf3-4383-83b9-7c2123afe412)
problem comes from this line:
```java
Files.write(spvFile.toPath(), compiledShader);
```
When i try to manually run the Jar it fails with this error:
```java
> cd .\booksamples\chapter-09\target\
> \booksamples\chapter-09\target> java -jar chapter-09-1.0.0.jar

> Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/vulkanb/Main has been compiled by a more recent version of the 
Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
```
vscode don't want to work with Java workspaces and therefore relative paths to shaders / assets don't work in it. Maybe there is short fix that can be used in code to convert relative path to absolute path? This bug probably will disappear if i install `idea` but problem will exist anyway for all other users of vscode.

**Comment by lwjglgamedev** [comment]
Hi, I will have a look. Can you tell me hoy yo do execute the examples from vscode? Please also report the OS you are using. When you try to execute it manually the problem is different. It seems that you are using an older java version. Which version it reports when using java —version

**Comment by lwjglgamedev** [comment]
Please see #85
